version: '3'
services:
  backend:
    container_name: taskify-backend  # Name for the backend container
    build:
      context: ./backend  # Ensure this is correct
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app  # Mount backend directory correctly
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/Taskify
    depends_on:
      - mongodb
    restart: unless-stopped  # Restart if it crashes but not on manual stop

  mongodb:
    container_name: taskify-mongodb  # Name for the MongoDB container
    image: mongo
    ports:
      - "27018:27017"
    restart: unless-stopped  # Restart policy for MongoDB
