version: '3'
services:
  backend:
    container_name: taskify-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/Taskify
    depends_on:
      - mongodb
    restart: unless-stopped

  frontend:
    container_name: taskify-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules  # Avoid mounting node_modules from the host
    ports:
      - "3000:3000"  # Assuming Next.js runs on port 3000 # Frontend talks to backend
    depends_on:
      - backend
    restart: unless-stopped

  mongodb:
    container_name: taskify-mongodb
    image: mongo
    ports:
      - "27017:27017"
    restart: unless-stopped
